services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connersant-build
    image: connersant-build:latest
    command: ["npm", "run", "build"]
    volumes:
      - ./dist:/app/dist